---
# tasks file for mysql

- name: Install MariaDB
  apt:
    name: mariadb-server
    state: present
    update_cache: yes

- name: Install python3-pip package
  apt:
    name: python3-pip
    state: present

- name: Install Ansible & pymysql
  pip:
    name: 
      - ansible
      - pymysql
    state: present

- name: Install community.mysql collection
  shell: ansible-galaxy collection install community.mysql

- name: Set mysql root pass
  shell: mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '{{ MYSQL_ROOT_PASSWORD }}';"

- name: Disable remote root login
  mysql_user:
      login_user: root
      login_password: "{{ MYSQL_ROOT_PASSWORD }}"
      user: root
      host: "{{ ansible_fqdn | lower }}"
      state: absent
  
- name: Remove anonymous users
  mysql_user:
      login_user: root
      login_password: "{{ MYSQL_ROOT_PASSWORD }}"
      user: ''
      host_all: yes
      state: absent

- name: Remove test database
  mysql_db: 
      login_user: root
      login_password: "{{ MYSQL_ROOT_PASSWORD }}"
      db: test
      state: absent
  register: remove_testdb

- name: Remove the test database 2
  community.mysql.mysql_query:
    login_user: root
    login_password: "{{ MYSQL_ROOT_PASSWORD }}"
    query: DELETE FROM mysql.db WHERE Db='test' OR Db='test\_%'
    login_unix_socket: /run/mysqld/mysqld.sock

- name: Reload database privileges
  community.mysql.mysql_query:
    login_user: root
    login_password: "{{ MYSQL_ROOT_PASSWORD }}"
    query: FLUSH PRIVILEGES
    login_unix_socket: /run/mysqld/mysqld.sock

- name: Create 'guacadb' database
  community.mysql.mysql_db:
    login_user: root
    login_password: "{{ MYSQL_ROOT_PASSWORD }}"
    name: "{{ GUACAMOLE_DB }}"
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock

- name: Create guaca_nachos user
  mysql_user:
    login_user: root
    login_password: "{{ MYSQL_ROOT_PASSWORD }}"
    name: "{{ GUACAMOLE_MYSQL_USER }}"
    password: "{{ GUACAMOLE_MYSQL_PASSWORD }}"
    priv: "{{ GUACAMOLE_DB }}.*:ALL"
    host: "%"

- name: Setup privilege for guaca_nachos user
  community.mysql.mysql_query:
    login_db: "{{ GUACAMOLE_DB }}"
    login_user: root
    login_password: "{{ MYSQL_ROOT_PASSWORD }}"
    query: GRANT ALL ON {{ GUACAMOLE_DB }}.* TO '{{ GUACAMOLE_MYSQL_USER }}'@'%'
    login_unix_socket: /run/mysqld/mysqld.sock

- name: Reload database privileges
  community.mysql.mysql_query:
    login_db: "{{ GUACAMOLE_DB }}"
    login_user: root
    login_password: "{{ MYSQL_ROOT_PASSWORD }}"
    query: FLUSH PRIVILEGES
    login_unix_socket: /run/mysqld/mysqld.sock

- name: Download JDBC extension
  get_url:
    url: https://downloads.apache.org/guacamole/1.5.5/binary/guacamole-auth-jdbc-1.5.5.tar.gz
    dest: /tmp/guacamole-auth-jdbc-1.5.5.tar.gz

- name: Unarchive JDBC extension
  ansible.builtin.unarchive:
    src: /tmp/guacamole-auth-jdbc-1.5.5.tar.gz
    dest: /tmp/guacamole-auth-jdbc-1.5.5
    remote_src: yes

- name: Copy JDBC in Apache Guacamole extension folder
  copy:
    src: /tmp/guacamole-auth-jdbc-1.5.5/mysql/guacamole-auth-jdbc-mysql-1.5.5.jar
    dest: /etc/guacamole/extensions/guacamole-auth-jdbc-mysql-1.5.5.jar
    remote_src: yes

- name: Download MySQL connector
  get_url:
    url: https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-j-9.1.0.tar.gz
    dest: /tmp/mysql-connector-j-9.1.0.tar.gz

- name: Unarchive MySQL connector
  ansible.builtin.unarchive:
    src: /tmp/mysql-connector-j-9.1.0.tar.gz
    dest: /tmp/mysql-connector-j-9.1.0
    remote_src: yes

- name: Copy MySQL connector in Apache Guacamole folder
  copy:
    src: /tmp/mysql-connector-j-9.1.0/mysql-connector-j-9.1.0.jar
    dest: /etc/guacamole/lib/mysql-connector-j-9.1.0.jar
    remote_src: yes

- name: Import database schema
  shell: cat /tmp/guacamole-auth-jdbc-1.5.5/mysql/schema/*.sql | mysql -u root -p{{ MYSQL_ROOT_PASSWORD }} guacadb

- name: Add database information in "guacamole.properties" file
  # copy:
  #   dest: /etc/guacamole/guacamole.properties
  #   content: |
  #     # MySQL
  #     mysql-hostname: 127.0.0.1
  #     mysql-port: 3306
  #     mysql-database: guacadb
  #     mysql-username: guaca_nachos
  #     mysql-password: P@ssword!
  blockinfile:
    path: /etc/guacamole/guacamole.properties
    prepend_newline: true
    block: |
      # MySQL
      mysql-hostname: 127.0.0.1
      mysql-port: 3306
      mysql-database: guacadb
      mysql-username: guaca_nachos
      mysql-password: P@ssword!

- name: Add database information in "guacd.conf" file
  blockinfile:
    path: /etc/guacamole/guacd.conf
    prepend_newline: true
    block: |
      [server] 
      bind_host = 0.0.0.0
      bind_port = 4822

- name: Restart tomcat service
  ansible.builtin.systemd_service:
    name: tomcat9
    state: restarted
    masked: no

- name: Restart guacd service
  ansible.builtin.systemd_service:
    name: guacd
    state: restarted
    masked: no

- name: Restart mariadb service
  ansible.builtin.systemd_service:
    name: mariadb
    state: restarted
    masked: no